### ISSUE TITLE
Could not find template 'fail2ban//etc/fail2ban/jail.conf.erb' - CentOS Linux release 7.6.1810 (Core)

### ISSUE THREAD

**Issue by 777dimas** [voxpupuli/puppet-fail2ban#102]
**CentOS Linux release 7.6.1810 (Core)**

Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, Could not find template 'fail2ban//etc/fail2ban/jail.conf.erb'

**Comment by bastelfreak** [comment]
Hi @777dimas, our latest merge worked fine on travis:
https://travis-ci.org/voxpupuli/puppet-fail2ban/builds/463560976?utm_source=github_status&utm_medium=notification

did you try the latest release / master branch? How do you include this module?

**Comment by 777dimas** [comment]
Hi.
Ok.I will try latest release / master branch...
Thanks.

**Comment by coreone** [comment]
I believe this is the issue I started seeing recently.  If so, the root of the problem is *lsb* packages on the OS. For example, on a RedHat-based system, this module requires the `redhat-lsb-core` package.  On Debian-based systems, it needs `lsb-release`.  Sometimes these packages are installed by default, but sometimes not.  In my case, they were not.

The problem with these packages is that, depending on the distribution, they can install a lot of unneeded software.  Additionally, the LSB packages are now a prerequisite for this package, but this package does not ensure that they are installed.

As for the Travis tests, I spent a fair bit of time trying to figure that out on tests for a module I wrote that has `puppet/fail2ban` as a dependency. I think the solution was that the Travis tests installed that package as part of their tests:

https://github.com/voxpupuli/puppet-fail2ban/blob/master/spec/spec_helper_acceptance.rb#L18-L21

https://travis-ci.org/voxpupuli/puppet-fail2ban/jobs/463560982#L1081-L1085

I think the real answer here is to get away from using "code names" and instead use `os` facts that are standard and come as part of the Puppet core.

**Comment by bastelfreak** [comment]
@coreone ah yes, you're correct. However, I did a quick grep for `lsbdistcodename` in our codebase and didn't found anything in the `manifests/` folder. Are you aware of any codeparts that need to be changed? If so, could you provide a PR for this?

**Comment by coreone** [comment]
Technically, it is not in a manifest, however the README instructs users to use that fact in every example that uses `config_file_template`.  We can get around this by hard-coding the codename for each OS on which we use this module.  However, organizing the templates directory around this fact just feels cumbersome.

I think at the very least there should be a note in the README, to prevent any confusion, that states that in order to use any of the examples with `lsbdistcodename`, one must install the LSB packages.

**Comment by dhoppe** [comment]
The problem should be solved, because the pull request #135 has removed the use of LSB facts.
