### ISSUE TITLE
ignoreip in custom jails  not populating

### ISSUE THREAD

**Issue by harisuseki** [voxpupuli/puppet-fail2ban#120]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.10.12
- Ruby: 2.1.0 (included with puppet)
- Distribution: Ubuntu 16.04
- Module version: 2.4.1

## How to reproduce (e.g Puppet code you use)
Add the line `ignoreip: ['127.0.0.1', '192.168.1.1/24']` for your custom jail as per documentation

## What are you seeing
in my custom jail, I get the following line for ignoreip:
`ignoreip = `

## What behaviour did you expect instead
I expected to see `ignoreip = 127.0.0.1 192.168.1.1/24` in my custom jail config file

## Any additional information you'd like to impart
If I modify templates/common/custom_jail.conf.epp and change the following line (line 25 for me) from:
`ignoreip = <% $ignoreip.join(' ') -%>`
to: 
`ignoreip = <%= $ignoreip.join(' ') -%>`

Then the ignoreip in my custom jail populates correctly.

**Comment by israelriibeiro** [comment]
I think the problem is how you configure your [fail2ban](https://github.com/voxpupuli/puppet-fail2ban#beginning-with-fail2ban) . My main problem is that i can't find the template.

Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, Could not find template 'fail2ban/xenial/etc/fail2ban/jail.conf.epp' at /etc/puppetlabs/code/environments/production/modules/fail2ban/manifests/init.pp:67:26 on node

**Comment by harisuseki** [comment]
That's an interesting idea, although I have had no errors regarding the module finding any templates. Also, as soon as I change the assignment variable in the custom jail template to include  the '=' (`ignoreip = <%= $ignoreip.join(' ') -%>`), the values are retrieved from the yaml and joined and populated correctly.

**Comment by dhoppe** [comment]
This problem has already been solved by #109.
