### ISSUE TITLE
Could not find template 'fail2ban/stretch/etc/fail2ban/jail.conf.erb'

### ISSUE THREAD

**Issue by brentclark** [voxpupuli/puppet-fail2ban#88]
Good day

It looks like templates are renamed to epp, but then you get 

Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, Could not find template 'fail2ban/stretch/etc/fail2ban/jail.conf.erb' (file: /etc/puppetlabs/code/modules/fail2ban/manifests/init.pp, line: 44, column: 26) on node REMOVED

**Comment by jreitmayer** [comment]
This is still an issue. Any word on how to fix it?

**Comment by jreitmayer** [comment]
make sure you add mod 'puppet-extlib', '3.0.0' to your puppet file to fix this.

**Comment by ikkaro** [comment]
Is not working, some update about this issue?

**Comment by Micsi** [comment]
same here. On a local run I get:

Error: /Stage[main]/Fail2ban::Config/File[fail2ban.dir]: Could not evaluate: Could not retrieve information from environment dev source(s) puppet:///modules/fail2ban/stretch/etc/fail2ban
Notice: /Stage[main]/Fail2ban::Config/File[/etc/fail2ban/action.d]: Dependency File[fail2ban.dir] has failures: true
Warning: /Stage[main]/Fail2ban::Config/File[/etc/fail2ban/action.d]: Skipping because of failed dependencies
Notice: /Stage[main]/Fail2ban::Config/File[/etc/fail2ban/action.d/apf.conf]: Dependency File[fail2ban.dir] has failures: true
Warning: /Stage[main]/Fail2ban::Config/File[/etc/fail2ban/action.d/apf.conf]: Skipping because of failed dependencies

as to the tip by @jreitmayer, adding puppet-extlib, now at 3.1.0 does not help (debian stretch)

**Comment by Micsi** [comment]
I am using code straight from the docs:

class { 'fail2ban':
    package_ensure => 'latest',
    config_dir_source => "puppet:///modules/fail2ban/${::lsbdistcodename}/etc/fail2ban",
  }

**Comment by dhoppe** [comment]
Which version of this module do you use? This issue should have been solved by #79.

**Comment by dhoppe** [comment]
The problem should be solved, because the pull request #135 has removed the use of LSB facts.
